- name: Build Yggdrasil
  community.general.make:
    chdir: "{{ base_repo_dir }}/source"
    target: srpm
    file: .copr/Makefile
    params:
      CGO_ENABLED: 0
      ARCH: "{{ build_arch }}"
      GOPROXY: "proxy.golang.org"
      PWD: "{{ base_repo_dir }}/source"
      spec: "{{ base_repo_dir }}/source"
      outdir: "{{ base_repo_dir }}/source"

- name: Check SRPM package 
  ansible.builtin.find:
    paths: "{{ base_repo_dir }}/source"
    patterns: '^yggdrasil-.*\.src\.rpm$'
    use_regex: yes
  register: package_version
  failed_when: package_version.matched != 1

- name: Install SRPM package
  ansible.builtin.command: "rpm -ihv {{ package_version.files[0].path }}"
  register: ret
  failed_when: ret.rc !=0

- name: Turn ELF binary stripping off in spec
  ansible.builtin.lineinfile:
    path: "{{ rpm_build_directory }}/SPECS/yggdrasil.spec"
    insertafter: '^'
    line: '%global __os_install_post %{nil}'
  when: "build_arch  == 'aarch64'"

- name: Run RPMBuild for Yggdrasil
  ansible.builtin.command: rpmbuild -bb {{ rpm_build_directory }}/SPECS/yggdrasil.spec --target {{ build_arch }}
