- name: Build binary for aarch64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: build-arm64

- name: Build RPM for aarch64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: rpm-arm64

- name: Build binary for x86_64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: build

- name: Build RPM for x86_64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: rpm
