- name: Build binary for aarch64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: build
  when: "build_arch == 'aarch64'"

- name: Build RPM for aarch64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: rpm
  when: "build_arch == 'aarch64'"

- name: Build binary for x86_64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: build
  when: "build_arch == 'x86_64'"

- name: Build RPM for x86_64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: rpm
  when: "build_arch == 'x86_64'"

- name: Capture RPM filename
  ansible.builtin.find:
    paths: "{{ rpm_build_directory }}/RPMS/"
    patterns: '^k4e-agent-.*\.rpm$'
    use_regex: yes
    recurse: yes
  register: agent_rpm
  failed_when: agent_rpm.matched != 2