- name: Build binary for aarch64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: build-arm64

- name: Build RPM for aarch64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: rpm-arm64

- name: Build binary for x86_64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: build
  
- name: Build RPM for x86_64
  community.general.make:
    chdir: "{{ base_repo_dir }}/worker"
    target: rpm

- name: Assert RPMs created
  ansible.builtin.find:
    paths: "{{ rpm_build_directory }}/RPMS/"
    patterns: '^k4e-agent-.*\.rpm$'
    use_regex: yes
    recurse: yes
  register: agent_rpm
  failed_when: agent_rpm.matched != 2